-- 코드를 입력하세요
SELECT  
    WAREHOUSE_ID,
    WAREHOUSE_NAME,
    ADDRESS,
    CASE 
        WHEN FREEZER_YN IS NULL THEN 'N'
        ELSE FREEZER_YN
    END FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS like '경기도%'